In [ ]:
import numpy as np
a=np.random.randint(0,50,10)
a

array([37, 36, 16,  2,  6, 42,  7, 11,  6, 39])

In [ ]:
np.random.randint(0,9,6)

array([6, 7, 4, 2, 5, 3])

In [ ]:
#create an array of 25 random numbers between 0 and 20 and apply the seed value of 13.

In [ ]:
np.random.seed(13)
arr=np.random.randint(0,20,25)
arr

array([18, 16, 10, 16,  6,  2, 12,  3,  2, 14,  5, 13, 10,  9, 11,  2,  0,
       19, 19, 11, 11,  1, 18, 11,  8])

In [ ]:
np.sort(arr)


array([ 0,  1,  2,  2,  2,  3,  5,  6,  8,  9, 10, 10, 11, 11, 11, 11, 12,
       13, 14, 16, 16, 18, 18, 19, 19])

In [ ]:
b=np.unique(arr)

In [ ]:
np.unique(a,return_counts=True)

(array([ 2,  6,  7, 11, 16, 36, 37, 39, 42]),
 array([1, 2, 1, 1, 1, 1, 1, 1, 1]))

In [ ]:
b

array([ 0,  1,  2,  3,  5,  6,  8,  9, 10, 11, 12, 13, 14, 16, 18, 19])

In [ ]:
c=np.append(b,5)

In [ ]:
c

array([ 0,  1,  2,  3,  5,  6,  8,  9, 10, 11, 12, 13, 14, 16, 18, 19,  5])

In [ ]:
d=np.power(c,2)
d

array([  0,   1,   4,   9,  25,  36,  64,  81, 100, 121, 144, 169, 196,
       256, 324, 361,  25])

In [ ]:
f=np.sqrt(d)
f

array([ 0.,  1.,  2.,  3.,  5.,  6.,  8.,  9., 10., 11., 12., 13., 14.,
       16., 18., 19.,  5.])

In [ ]:
np.zeros(2)

array([0., 0.])

In [ ]:
np.ones(2)

array([1., 1.])

In [ ]:
np.ones(2,dtype=np.int16)

array([1, 1], dtype=int16)

In [ ]:
np.ones([2,2],dtype=np.int16)

array([[1, 1],
       [1, 1]], dtype=int16)

In [ ]:
arr


array([ 0,  1,  2,  2,  2,  3,  5,  6,  8,  9, 10, 10, 11, 11, 11, 11, 12,
       13, 14, 16, 16, 18, 18, 19, 19])

In [ ]:
arr.sum()

247

In [ ]:
arr.min()

0

In [ ]:
arr.max()

19

In [ ]:
arr.mean()

9.88

In [ ]:
#np.arange and np.linspace

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(3,30,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
#create an array to get the numbers 1,5,9,13,17,21,25

In [ ]:
np.arange(1,28,4)

array([ 1,  5,  9, 13, 17, 21, 25])

In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.arange(9,dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
a1=np.arange(9,dtype=float).reshape(3,3)
a1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
b1=np.array([10,9,8])

In [ ]:
np.add(a1,b1)

array([[10., 10., 10.],
       [13., 13., 13.],
       [16., 16., 16.]])

In [ ]:
np.multiply(a1,b1)

array([[ 0.,  9., 16.],
       [30., 36., 40.],
       [60., 63., 64.]])

In [ ]:
g=np.divide(a1,b1)
g

array([[0.        , 0.11111111, 0.25      ],
       [0.3       , 0.44444444, 0.625     ],
       [0.6       , 0.77777778, 1.        ]])

In [ ]:
np.subtract(a1,b1)

array([[-10.,  -8.,  -6.],
       [ -7.,  -5.,  -3.],
       [ -4.,  -2.,   0.]])

In [ ]:
np.reciprocal(g)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in reciprocal
  """Entry point for launching an IPython kernel.


array([[       inf, 9.        , 4.        ],
       [3.33333333, 2.25      , 1.6       ],
       [1.66666667, 1.28571429, 1.        ]])